spring:
  datasource:
    source:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/samh_comic?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowMultiQueries=true
      username: root
      password: Wk3242020

#是否开启swagger
swagger:
  enable: true

logback:
  level: INFO
  log_path: ../SpringBootDemo/src/main/resources/log/
